name:                evm-hs
version:             0.1.0.0
github:              "lsankar4033/evm-hs"
license:             BSD3
author:              "lakshmansankar"
maintainer:          "lsankar4033@gmail.com"
copyright:           "2020 lakshmansankar"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lsankar4033/evm-hs#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  evm-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - evm-hs

tests:
  evm-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - evm-hs
